twig:
  default_path: "%kernel.project_dir%/templates"
  debug: "%kernel.debug%"
  strict_variables: false #'%kernel.debug%'
  form_themes: ["bootstrap_4_layout.html.twig"]
  paths:
    "templates": ~
